name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  base_image:
    strategy:
      matrix:
        codename:
          - focal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
